version: '3'
services:
  db1:
    image: mysql:5.7.22
    ports:
      - "3306:3306"
    env_file:
      - db-default.env
    volumes:
      - ./mysql/db-init.sql:/docker-entrypoint-initdb.d/db-init.sql
  db2:
    image: mysql:5.7.22
    ports:
      - "3307:3306"
    env_file:
      - db-default.env
    volumes:
      - ./mysql/db-init.sql:/docker-entrypoint-initdb.d/db-init.sql
  db3:
    image: mysql:5.7.22
    ports:
      - "3308:3306"
    env_file:
      - db-default.env
    volumes:
      - ./mysql/db-init.sql:/docker-entrypoint-initdb.d/db-init.sql
