version: '3'
services:
  db1:
    build:
      context: ./mysql-dev
      dockerfile: Dockerfile
    image: mysql-dev:0.1.0
    ports:
      - "3306:3306"
    env_file:
      - db-default.env
    volumes:
      - ./mysql/db-init.sql:/docker-entrypoint-initdb.d/db-init.sql
      - ./mysql/db-master.sql:/docker-entrypoint-initdb.d/db-master.sql
  db2:
    image: mysql-dev:0.1.0
    ports:
      - "3307:3306"
    env_file:
      - db-default.env
    volumes:
      - ./mysql/db-init.sql:/docker-entrypoint-initdb.d/db-init.sql
  db3:
    image: mysql-dev:0.1.0
    ports:
      - "3308:3306"
    env_file:
      - db-default.env
    volumes:
      - ./mysql/db-init.sql:/docker-entrypoint-initdb.d/db-init.sql
